In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
cd drive

/content/drive


In [3]:
cd MyDrive

/content/drive/MyDrive


In [4]:
cd Data

/content/drive/MyDrive/Data


In [5]:
import pandas as pd
non_PRC = pd.read_csv('stand/stand.csv')
PRC = pd.read_csv('stand/stand_par.csv')
clinical_assessment = pd.read_excel('Clinical Assessment.xlsx')

In [6]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.metrics import confusion_matrix, roc_auc_score, roc_curve
from sklearn.model_selection import GridSearchCV,cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
import warnings
from sklearn.feature_selection import RFE
from sklearn.metrics import accuracy_score, classification_report
import matplotlib.pyplot as plt

In [7]:
score = clinical_assessment.iloc[:,9]

In [8]:
del score[0]
del score[1]
del score[2]
del score[3]
del score[7]
del score[9]
del score[10]
del score[13]
del score[15]
del score[16]
del score[17]
del score[18]
del score[19]
del score[20]
del score[21]
del score[22]
del score[23]
del score[24]
del score[25]
del score[26]
del score[27]
del score[31]
del score[34]
del score[36]
del score[39]
del score[44]
del score[45]

In [9]:
y = []
for value in score:
    if value >= 45:
        y.append(1)
    else:
        y.append(0)
print(y)

[1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [17]:
## BBS High
print('BBS High:', y.count(1))
## BBS Low
print('BBS Low:', y.count(0))

BBS High: 14
BBS Low: 5


## Non-paretic Side

In [18]:
df_non = pd.DataFrame(non_PRC)
y = pd.DataFrame(y)
non = pd.concat([y,df_non],axis=1)
colname = list(non.columns)
colname[0] = "score"
non.columns = colname
non.columns

Index(['score', 'Unnamed: 0', 'PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7',
       'PC8', 'PC9', 'PC10', 'PC11', 'PC12', 'PC13', 'PC14', 'PC15', 'PC16',
       'PC17', 'PC18', 'PC19'],
      dtype='object')

In [19]:
# 상수항 없이 내용
X = non.loc[:,['PC2','PC10','PC15']]
y = non['score']
import statsmodels.api as sm
reg = sm.Logit(y,X).fit()
print(reg.summary())
print(np.exp(reg.params))

Optimization terminated successfully.
         Current function value: 0.364835
         Iterations 7
                           Logit Regression Results                           
Dep. Variable:                  score   No. Observations:                   19
Model:                          Logit   Df Residuals:                       16
Method:                           MLE   Df Model:                            2
Date:                Wed, 24 Jan 2024   Pseudo R-squ.:                  0.3670
Time:                        07:46:20   Log-Likelihood:                -6.9319
converged:                       True   LL-Null:                       -10.950
Covariance Type:            nonrobust   LLR p-value:                   0.01798
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
PC2           -0.1104      0.055     -2.005      0.045      -0.218      -0.002
PC10           0.1589      0.

In [38]:
# 상수항 추가한 내용(오류)
X = non.loc[:,['PC2','PC10','PC15']]
y = non['score']
X = sm.add_constant(X,has_constant="add")
logit = sm.Logit(y, X)
result = logit.fit()
print(result.summary2())

         Current function value: 0.000000
         Iterations: 35
                          Results: Logit
Model:              Logit            Method:           MLE        
Dependent Variable: score            Pseudo R-squared: 1.000      
Date:               2024-01-24 07:55 AIC:              8.0000     
No. Observations:   19               BIC:              11.7778    
Df Model:           3                Log-Likelihood:   -1.3899e-09
Df Residuals:       15               LL-Null:          -10.950    
Converged:          0.0000           LLR p-value:      6.8409e-05 
No. Iterations:     35.0000          Scale:            1.0000     
------------------------------------------------------------------
       Coef.     Std.Err.     z    P>|z|     [0.025       0.975]  
------------------------------------------------------------------
const  90.4611 111877.3123  0.0008 0.9994 -219185.0418 219365.9639
PC2    -4.8530   6592.5047 -0.0007 0.9994  -12925.9249  12916.2189
PC10   10.2718  13171.

/usr/local/lib/python3.10/dist-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/usr/local/lib/python3.10/dist-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/usr/local/lib/python3.10/dist-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/usr/local/lib/python3.10/dist-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/usr/local/lib/python3.10/dist-packa

In [21]:
X = non.loc[:,['PC2','PC10','PC15']]
y = non['score']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=123, stratify=y)

### logistic regression

In [22]:
lr_model = LogisticRegression()

# 선택된 특성으로 모델 학습
lr_model.fit(X_train, y_train)

y_pred_lr = lr_model.predict(X_test)

conf_matrix = confusion_matrix(y_test, y_pred_lr)
print("Confusion Matrix:\n", conf_matrix)
# 정확도 계산
accuracy_lr = accuracy_score(y_test, y_pred_lr)
print("Test Accuracy:", accuracy_lr)

# f1-score 계산
f1_lr = f1_score(y_test, y_pred_lr)
print("f1-score:", f1_lr)

# auc 계산
auc_lr = roc_auc_score(y_test,y_pred_lr)
print("AUC:",auc_lr)

# 분류 보고서 출력
classification_rep_lr = classification_report(y_test, y_pred_lr)
print("Classification Report:\n", classification_rep_lr)

Confusion Matrix:
 [[1 1]
 [0 6]]
Test Accuracy: 0.875
f1-score: 0.923076923076923
AUC: 0.75
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       0.86      1.00      0.92         6

    accuracy                           0.88         8
   macro avg       0.93      0.75      0.79         8
weighted avg       0.89      0.88      0.86         8



### Random Forest

In [23]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier


param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}


grid_search = GridSearchCV(RandomForestClassifier(random_state=123), param_grid, cv=3, scoring='accuracy')


grid_search.fit(X_train, y_train)


best_rf_model = grid_search.best_estimator_
best_params = grid_search.best_params_
print("Best Random Forest Model:", best_rf_model)
print("Best Hyperparameters:", best_params)

y_pred_best_rf = best_rf_model.predict(X_test)


conf_matrix_best = confusion_matrix(y_test, y_pred_best_rf)
print("Confusion Matrix:\n", conf_matrix_best)

accuracy_best_rf = accuracy_score(y_test, y_pred_best_rf)
print("Test Accuracy with Best Model:", accuracy_best_rf)

f1_best_rf = f1_score(y_test, y_pred_best_rf)
print("f1-score with Best Model:", f1_best_rf)

auc_best_rf = roc_auc_score(y_test, y_pred_best_rf)
print("AUC with Best Model:", auc_best_rf)

classification_rep_best_rf = classification_report(y_test, y_pred_best_rf)
print("Classification Report with Best Model:\n", classification_rep_best_rf)

Best Random Forest Model: RandomForestClassifier(min_samples_split=5, random_state=123)
Best Hyperparameters: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 100}
Confusion Matrix:
 [[1 1]
 [0 6]]
Test Accuracy with Best Model: 0.875
f1-score with Best Model: 0.923076923076923
AUC with Best Model: 0.75
Classification Report with Best Model:
               precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       0.86      1.00      0.92         6

    accuracy                           0.88         8
   macro avg       0.93      0.75      0.79         8
weighted avg       0.89      0.88      0.86         8



### SVM Linear

In [24]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

param_grid = {
    'C': [0.1, 1, 10],
    'kernel': ['linear'],
    'degree':[2,3,4]
}


grid_search = GridSearchCV(SVC(random_state=123), param_grid, cv=3, scoring='accuracy')


grid_search.fit(X_train, y_train)


best_svm_model = grid_search.best_estimator_
best_params = grid_search.best_params_
print("Best SVM Model:", best_svm_model)
print("Best Hyperparameters:", best_params)


y_pred_best_svm_linear = best_svm_model.predict(X_test)


conf_matrix_best = confusion_matrix(y_test, y_pred_best_svm_linear)
print("Confusion Matrix:\n", conf_matrix_best)

accuracy_best_svm_linear = accuracy_score(y_test, y_pred_best_svm_linear)
print("Test Accuracy with Best Model:", accuracy_best_svm_linear)

f1_best_svm_linear = f1_score(y_test, y_pred_best_svm_linear)
print("f1-score with Best Model:", f1_best_svm_linear)

y_scores_best_svm = best_svm_model.decision_function(X_test)
auc_best_svm_linear = roc_auc_score(y_test, y_scores_best_svm)
print("AUC with Best Model:", auc_best_svm_linear)

classification_rep_best_svm_linear = classification_report(y_test, y_pred_best_svm_linear)
print("Classification Report with Best Model:\n", classification_rep_best_svm_linear)

Best SVM Model: SVC(C=0.1, degree=2, kernel='linear', random_state=123)
Best Hyperparameters: {'C': 0.1, 'degree': 2, 'kernel': 'linear'}
Confusion Matrix:
 [[1 1]
 [0 6]]
Test Accuracy with Best Model: 0.875
f1-score with Best Model: 0.923076923076923
AUC with Best Model: 0.9166666666666667
Classification Report with Best Model:
               precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       0.86      1.00      0.92         6

    accuracy                           0.88         8
   macro avg       0.93      0.75      0.79         8
weighted avg       0.89      0.88      0.86         8



### SVM Poly

In [25]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

param_grid = {
    'C': [0.1, 1, 10],
    'kernel': ['poly'],
    'degree': [2, 3, 4],
}


grid_search = GridSearchCV(SVC(random_state=123), param_grid, cv=3, scoring='accuracy')


grid_search.fit(X_train, y_train)


best_svm_model = grid_search.best_estimator_
best_params = grid_search.best_params_
print("Best SVM Model:", best_svm_model)
print("Best Hyperparameters:", best_params)


y_pred_best_svm_poly = best_svm_model.predict(X_test)


conf_matrix_best = confusion_matrix(y_test, y_pred_best_svm_poly)
print("Confusion Matrix:\n", conf_matrix_best)

accuracy_best_svm_poly = accuracy_score(y_test, y_pred_best_svm_poly)
print("Test Accuracy with Best Model:", accuracy_best_svm_poly)

f1_best_svm_poly = f1_score(y_test, y_pred_best_svm_poly)
print("f1-score with Best Model:", f1_best_svm_poly)

y_scores_best_svm_poly = best_svm_model.decision_function(X_test)
auc_best_svm_poly = roc_auc_score(y_test, y_scores_best_svm_poly)
print("AUC with Best Model:", auc_best_svm_poly)

classification_rep_best_svm_poly = classification_report(y_test, y_pred_best_svm_poly)
print("Classification Report with Best Model:\n", classification_rep_best_svm_poly)

Best SVM Model: SVC(C=0.1, kernel='poly', random_state=123)
Best Hyperparameters: {'C': 0.1, 'degree': 3, 'kernel': 'poly'}
Confusion Matrix:
 [[0 2]
 [0 6]]
Test Accuracy with Best Model: 0.75
f1-score with Best Model: 0.8571428571428571
AUC with Best Model: 0.8333333333333333
Classification Report with Best Model:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.75      1.00      0.86         6

    accuracy                           0.75         8
   macro avg       0.38      0.50      0.43         8
weighted avg       0.56      0.75      0.64         8



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### XGBoost

In [26]:
from sklearn.model_selection import GridSearchCV
import xgboost as xgb


param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 4, 5],
    'learning_rate': [0.01, 0.1, 0.2],
}


grid_search = GridSearchCV(xgb.XGBClassifier(random_state=123), param_grid, cv=3, scoring='accuracy')


grid_search.fit(X_train, y_train)


best_xgb_model = grid_search.best_estimator_
best_params = grid_search.best_params_
print("Best XGBoost Model:", best_xgb_model)
print("Best Hyperparameters:", best_params)


y_pred_best_xgb = best_xgb_model.predict(X_test)

conf_matrix_best = confusion_matrix(y_test, y_pred_best_xgb)
print("Confusion Matrix:\n", conf_matrix_best)

accuracy_best_xgb = accuracy_score(y_test, y_pred_best_xgb)
print("Test Accuracy with Best Model:", accuracy_best_xgb)

f1_best_xgb = f1_score(y_test, y_pred_best_xgb)
print("f1-score with Best Model:", f1_best_xgb)

auc_best_xgb = roc_auc_score(y_test, y_pred_best_xgb)
print("AUC with Best Model:", auc_best_xgb)

classification_rep_best_xgb = classification_report(y_test, y_pred_best_xgb)
print("Classification Report with Best Model:\n", classification_rep_best_xgb)

Best XGBoost Model: XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.01, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, random_state=123, ...)
Best Hyperparameters: {'learning_rate': 0.01, 'max_depth': 3, 'n_estimators': 100}
Confusion Matrix:
 [[0 2]
 [0 6]]
Test Accuracy with Best Model: 0.75
f1-score with Best Model: 0.8571428571428571
AUC with Best Model: 0.5
Clas

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## paretic-Side

In [27]:
df_par = pd.DataFrame(PRC)
y = pd.DataFrame(y)
par = pd.concat([y,df_par],axis=1)
colname = list(par.columns)
colname[0] = "score"

In [28]:
# 상수항 없는 식
import random
random.seed(1)
X = par.loc[:,['PC1','PC7','PC17']]
y = par['score']
import statsmodels.api as sm
reg = sm.Logit(y,X).fit()
print(reg.summary())
print(np.exp(reg.params))

Optimization terminated successfully.
         Current function value: 0.493811
         Iterations 6
                           Logit Regression Results                           
Dep. Variable:                  score   No. Observations:                   19
Model:                          Logit   Df Residuals:                       16
Method:                           MLE   Df Model:                            2
Date:                Wed, 24 Jan 2024   Pseudo R-squ.:                  0.1432
Time:                        07:47:40   Log-Likelihood:                -9.3824
converged:                       True   LL-Null:                       -10.950
Covariance Type:            nonrobust   LLR p-value:                    0.2085
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
PC1           -0.0217      0.013     -1.681      0.093      -0.047       0.004
PC7            0.1078      0.

In [29]:
## PC17이 유의하지 않으므로 PC17 제거 후 다시

import random
random.seed(1)
X = par.loc[:,['PC1','PC7']]
y = par['score']
import statsmodels.api as sm
reg = sm.Logit(y,X).fit()
print(reg.summary())
print(np.exp(reg.params))

Optimization terminated successfully.
         Current function value: 0.532142
         Iterations 6
                           Logit Regression Results                           
Dep. Variable:                  score   No. Observations:                   19
Model:                          Logit   Df Residuals:                       17
Method:                           MLE   Df Model:                            1
Date:                Wed, 24 Jan 2024   Pseudo R-squ.:                 0.07668
Time:                        07:47:40   Log-Likelihood:                -10.111
converged:                       True   LL-Null:                       -10.950
Covariance Type:            nonrobust   LLR p-value:                    0.1950
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
PC1           -0.0183      0.011     -1.649      0.099      -0.040       0.003
PC7            0.0954      0.

In [30]:
## 상수항 추가
import random
random.seed(1)
X = par.loc[:,['PC1','PC7','PC17']]
y = par['score']
X = sm.add_constant(X,has_constant="add")
logit = sm.Logit(y, X)
result = logit.fit()
print(result.summary2())

Optimization terminated successfully.
         Current function value: 0.390431
         Iterations 7
                        Results: Logit
Model:              Logit            Method:           MLE     
Dependent Variable: score            Pseudo R-squared: 0.323   
Date:               2024-01-24 07:47 AIC:              22.8364 
No. Observations:   19               BIC:              26.6141 
Df Model:           3                Log-Likelihood:   -7.4182 
Df Residuals:       15               LL-Null:          -10.950 
Converged:          1.0000           LLR p-value:      0.069875
No. Iterations:     7.0000           Scale:            1.0000  
-----------------------------------------------------------------
          Coef.    Std.Err.     z      P>|z|     [0.025    0.975]
-----------------------------------------------------------------
const     6.1671     3.5323   1.7459   0.0808   -0.7561   13.0903
PC1       0.0937     0.0656   1.4287   0.1531   -0.0348    0.2222
PC7       0.0703 

In [31]:
## 상수항 추가했을때 PC7,PC17 유의하지 않음
import random
random.seed(1)
X = par.loc[:,['PC1']]
y = par['score']
import statsmodels.api as sm
X = sm.add_constant(X,has_constant="add")
logit = sm.Logit(y, X)
result = logit.fit()
print(result.summary2())
print(np.exp(result.params))

Optimization terminated successfully.
         Current function value: 0.453182
         Iterations 6
                        Results: Logit
Model:              Logit            Method:           MLE     
Dependent Variable: score            Pseudo R-squared: 0.214   
Date:               2024-01-24 07:47 AIC:              21.2209 
No. Observations:   19               BIC:              23.1098 
Df Model:           1                Log-Likelihood:   -8.6105 
Df Residuals:       17               LL-Null:          -10.950 
Converged:          1.0000           LLR p-value:      0.030519
No. Iterations:     6.0000           Scale:            1.0000  
-----------------------------------------------------------------
          Coef.    Std.Err.     z      P>|z|     [0.025    0.975]
-----------------------------------------------------------------
const     6.9288     3.2385   2.1395   0.0324    0.5814   13.2761
PC1       0.1159     0.0613   1.8915   0.0586   -0.0042    0.2361

const    1021.24

In [32]:
import random
random.seed(1)
X = par.loc[:,['PC1','PC7','PC17']]
y = par['score']
X_train , X_test , y_train , y_test  = train_test_split(X,y,test_size = 0.4,random_state=123,stratify=y)

### logistic regression

In [33]:
lr_model = LogisticRegression()

lr_model.fit(X_train, y_train)

y_pred_par_lr = lr_model.predict(X_test)

conf_matrix = confusion_matrix(y_test, y_pred_par_lr)
print("Confusion Matrix:\n", conf_matrix)
# 정확도 계산
accuracy_lr_ps = accuracy_score(y_test, y_pred_par_lr)
print("Test Accuracy:", accuracy_lr_ps)

# f1-score 계산
f1_lr_ps = f1_score(y_test, y_pred_par_lr)
print("f1-score:", f1_lr_ps)

# AUC 계산
auc_lr_ps = roc_auc_score(y_test,y_pred_par_lr)
print("AUC:",auc_lr_ps)


classification_rep_lr = classification_report(y_test, y_pred_par_lr)
print("Classification Report:\n", classification_rep_lr)

Confusion Matrix:
 [[1 1]
 [1 5]]
Test Accuracy: 0.75
f1-score: 0.8333333333333334
AUC: 0.6666666666666667
Classification Report:
               precision    recall  f1-score   support

           0       0.50      0.50      0.50         2
           1       0.83      0.83      0.83         6

    accuracy                           0.75         8
   macro avg       0.67      0.67      0.67         8
weighted avg       0.75      0.75      0.75         8



### paretic RandomForest

In [34]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}


grid_search = GridSearchCV(RandomForestClassifier(random_state=123), param_grid, cv=3, scoring='accuracy')


grid_search.fit(X_train, y_train)

# 최적의 모델과 하이퍼파라미터 출력
best_rf_model = grid_search.best_estimator_
best_params = grid_search.best_params_
print("Best Random Forest Model:", best_rf_model)
print("Best Hyperparameters:", best_params)

# 최적의 모델로 테스트 데이터에 대한 예측 수행
y_pred_best_par_rf = best_rf_model.predict(X_test)

# 성능 메트릭 계산
conf_matrix_best = confusion_matrix(y_test, y_pred_best_par_rf)
print("Confusion Matrix:\n", conf_matrix_best)

accuracy_best_par_rf = accuracy_score(y_test, y_pred_best_par_rf)
print("Test Accuracy with Best Model:", accuracy_best_par_rf)

f1_best_par_rf = f1_score(y_test, y_pred_best_par_rf)
print("F1-score with Best Model:", f1_best_par_rf)

auc_best_par_rf = roc_auc_score(y_test, y_pred_best_par_rf)
print("AUC with Best Model:", auc_best_par_rf)

classification_rep_best_par_rf = classification_report(y_test, y_pred_best_par_rf)
print("Classification Report with Best Model:\n", classification_rep_best_par_rf)

Best Random Forest Model: RandomForestClassifier(random_state=123)
Best Hyperparameters: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 100}
Confusion Matrix:
 [[2 0]
 [2 4]]
Test Accuracy with Best Model: 0.75
F1-score with Best Model: 0.8
AUC with Best Model: 0.8333333333333333
Classification Report with Best Model:
               precision    recall  f1-score   support

           0       0.50      1.00      0.67         2
           1       1.00      0.67      0.80         6

    accuracy                           0.75         8
   macro avg       0.75      0.83      0.73         8
weighted avg       0.88      0.75      0.77         8



### paretic SVM Linear

In [35]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

param_grid = {
    'C': [0.1, 1, 10],
    'kernel': ['linear'],
    'degree':[2,3,4]
}


grid_search = GridSearchCV(SVC(random_state=123), param_grid, cv=3, scoring='accuracy')


grid_search.fit(X_train, y_train)


best_svm_model = grid_search.best_estimator_
best_params = grid_search.best_params_
print("Best SVM Model:", best_svm_model)
print("Best Hyperparameters:", best_params)


y_pred_best_par_svm_linear = best_svm_model.predict(X_test)

# 성능 메트릭 계산
conf_matrix_best = confusion_matrix(y_test, y_pred_best_par_svm_linear)
print("Confusion Matrix:\n", conf_matrix_best)

accuracy_best_par_svm_linear = accuracy_score(y_test, y_pred_best_par_svm_linear)
print("Test Accuracy with Best Model:", accuracy_best_par_svm_linear)

f1_best_par_svm_linear = f1_score(y_test, y_pred_best_par_svm_linear)
print("F1-score with Best Model:", f1_best_par_svm_linear)

y_scores_best_par_svm_linear = best_svm_model.decision_function(X_test)
auc_best_par_svm_linear = roc_auc_score(y_test, y_scores_best_par_svm_linear)
print("AUC with Best Model:", auc_best_par_svm_linear)

classification_rep_best_par_svm = classification_report(y_test, y_pred_best_par_svm_linear)
print("Classification Report with Best Model:\n", classification_rep_best_par_svm)

Best SVM Model: SVC(C=0.1, degree=2, kernel='linear', random_state=123)
Best Hyperparameters: {'C': 0.1, 'degree': 2, 'kernel': 'linear'}
Confusion Matrix:
 [[2 0]
 [0 6]]
Test Accuracy with Best Model: 1.0
F1-score with Best Model: 1.0
AUC with Best Model: 1.0
Classification Report with Best Model:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         6

    accuracy                           1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8



### paretic SVM Poly

In [36]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

param_grid = {
    'C': [0.1, 1, 10],
    'kernel': ['poly'],
    'degree': [2, 3, 4],
}


grid_search = GridSearchCV(SVC(random_state=123), param_grid, cv=3, scoring='accuracy')


grid_search.fit(X_train, y_train)


best_svm_model = grid_search.best_estimator_
best_params = grid_search.best_params_
print("Best SVM Model:", best_svm_model)
print("Best Hyperparameters:", best_params)


y_pred_best_par_svm_poly = best_svm_model.predict(X_test)

# 성능 메트릭 계산
conf_matrix_best = confusion_matrix(y_test, y_pred_best_par_svm_poly)
print("Confusion Matrix:\n", conf_matrix_best)

accuracy_best_par_svm_poly = accuracy_score(y_test, y_pred_best_par_svm_poly)
print("Test Accuracy with Best Model:", accuracy_best_par_svm_poly)

f1_best_par_svm_poly = f1_score(y_test, y_pred_best_par_svm_poly)
print("F1-score with Best Model:", f1_best_par_svm_poly)

y_scores_best_par_svm_poly = best_svm_model.decision_function(X_test)
auc_best_par_svm_poly = roc_auc_score(y_test, y_scores_best_par_svm_poly)
print("AUC with Best Model:", auc_best_par_svm_poly)

classification_rep_best_par_svm = classification_report(y_test, y_pred_best_par_svm_poly)
print("Classification Report with Best Model:\n", classification_rep_best_par_svm)

Best SVM Model: SVC(C=0.1, degree=2, kernel='poly', random_state=123)
Best Hyperparameters: {'C': 0.1, 'degree': 2, 'kernel': 'poly'}
Confusion Matrix:
 [[0 2]
 [0 6]]
Test Accuracy with Best Model: 0.75
F1-score with Best Model: 0.8571428571428571
AUC with Best Model: 1.0
Classification Report with Best Model:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.75      1.00      0.86         6

    accuracy                           0.75         8
   macro avg       0.38      0.50      0.43         8
weighted avg       0.56      0.75      0.64         8



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### paretic XGBoost

In [37]:
from sklearn.model_selection import GridSearchCV
import xgboost as xgb


param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 4, 5],
    'learning_rate': [0.01, 0.1, 0.2],
}


grid_search = GridSearchCV(xgb.XGBClassifier(random_state=123), param_grid, cv=3, scoring='accuracy')


grid_search.fit(X_train, y_train)


best_xgb_model = grid_search.best_estimator_
best_params = grid_search.best_params_
print("Best XGBoost Model:", best_xgb_model)
print("Best Hyperparameters:", best_params)


y_pred_best_par_xgb = best_xgb_model.predict(X_test)

conf_matrix_best = confusion_matrix(y_test, y_pred_best_par_xgb)
print("Confusion Matrix:\n", conf_matrix_best)

accuracy_best_par_xgb = accuracy_score(y_test, y_pred_best_par_xgb)
print("Test Accuracy with Best Model:", accuracy_best_par_xgb)

f1_best_par_xgb = f1_score(y_test, y_pred_best_par_xgb)
print("F1-score with Best Model:", f1_best_par_xgb)

auc_best_par_xgb = roc_auc_score(y_test, y_pred_best_par_xgb)
print("AUC with Best Model:", auc_best_par_xgb)

classification_rep_best_par_xgb = classification_report(y_test, y_pred_best_par_xgb)
print("Classification Report with Best Model:\n", classification_rep_best_par_xgb)

Best XGBoost Model: XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.01, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, random_state=123, ...)
Best Hyperparameters: {'learning_rate': 0.01, 'max_depth': 3, 'n_estimators': 100}
Confusion Matrix:
 [[0 2]
 [0 6]]
Test Accuracy with Best Model: 0.75
F1-score with Best Model: 0.8571428571428571
AUC with Best Model: 0.5
Clas

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
